### ISSUE TITLE
Announcement 
We are going to start this project back, on coming Tuesday (13-12-22) 

### ISSUE THREAD

**Issue by configure-lol** [DoduCode/Shmup#3]
•Game name : (not yet decided)
•It's like a plane goes higher and higher and it slowly converts into a rocket and then a super rocket and it goes on......
•There will be rewards like points and coins
• **In game purchases are not yet decided **
•We Will be taking references from, like a rocket ship game 
•Multiplayer is not yet decided
**NOTE :
this is just brief information about the game the actually design of the game will be shared later on **
(If you guys want to add any more points pls add them)

@DoduCode  look after this announcement

**Comment by DoduCode** [comment]
This aint chat
